name: Release Published
on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: node-red/node-red
          path: node-red
      - name: "install"
        run: npm install
      - name: "build"
        run: npm build --src=node-red
      - name: "clean up Node-RED"
        run: rm -rf node-red
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_PUBLISH_TOKEN }}
          access: public
